# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contrabass < Formula
  desc "A project-level orchestrator for AI coding agents"
  homepage "https://github.com/junhoyeo/contrabass"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.1.0/contrabass_0.1.0_darwin_amd64.tar.gz"
      sha256 "948ba12aef876ecebefec939860cacdde13bdf5764ff66eb89f79ff82ff33a78"

      define_method(:install) do
        bin.install "contrabass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.1.0/contrabass_0.1.0_darwin_arm64.tar.gz"
      sha256 "9e924f3aff313f9f121e2fd4d77f7717b5af800ec4e3edbdfd334c0443591b2c"

      define_method(:install) do
        bin.install "contrabass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.1.0/contrabass_0.1.0_linux_amd64.tar.gz"
      sha256 "100b19c76e37dd6ef3fb966da04be1c9711e294340d77c4851a8f16cfec496f3"
      define_method(:install) do
        bin.install "contrabass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.1.0/contrabass_0.1.0_linux_arm64.tar.gz"
      sha256 "d3c4a1b989c8f4c274bf1ffdbafb4e1f1aaec381f69ec0a579573f9a973669c8"
      define_method(:install) do
        bin.install "contrabass"
      end
    end
  end
end
