# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contrabass < Formula
  desc "A project-level orchestrator for AI coding agents"
  homepage "https://github.com/junhoyeo/contrabass"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.2.2/contrabass_0.2.2_darwin_amd64.tar.gz"
      sha256 "eb9b3ddaa61d5a8079c2c0b848280730cce5731d8d32ed6a941d747902cbd80f"

      define_method(:install) do
        bin.install "contrabass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.2.2/contrabass_0.2.2_darwin_arm64.tar.gz"
      sha256 "3c25d9ef8e4feeaf2c9425263b7cfbcc890efac181b2721751aae4edbe2ae3de"

      define_method(:install) do
        bin.install "contrabass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.2.2/contrabass_0.2.2_linux_amd64.tar.gz"
      sha256 "4e79db7f6f76b8990c052d6a9378e8d48befb231cfd37cb0047fb0220c4f48fd"
      define_method(:install) do
        bin.install "contrabass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.2.2/contrabass_0.2.2_linux_arm64.tar.gz"
      sha256 "1109e44f73822be2fe4fc168471d51c590ca5a3719d380e395936a6ecb59fb3c"
      define_method(:install) do
        bin.install "contrabass"
      end
    end
  end
end
