# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contrabass < Formula
  desc "A project-level orchestrator for AI coding agents"
  homepage "https://github.com/junhoyeo/contrabass"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.1.1/contrabass_0.1.1_darwin_amd64.tar.gz"
      sha256 "1fed94e1f5c6bf7c7fbb2fd3815634ffdcaa414323676b315b50eab9c8ca8cb1"

      define_method(:install) do
        bin.install "contrabass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.1.1/contrabass_0.1.1_darwin_arm64.tar.gz"
      sha256 "1fe8bd186b8d5147080e7e3b03073fab9544afd1bb40775b21338658b8b31194"

      define_method(:install) do
        bin.install "contrabass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.1.1/contrabass_0.1.1_linux_amd64.tar.gz"
      sha256 "930eddd9ab322eb6e811f39c8c12b15d805d5710df6062990fb74eaf59f3e134"
      define_method(:install) do
        bin.install "contrabass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/junhoyeo/contrabass/releases/download/v0.1.1/contrabass_0.1.1_linux_arm64.tar.gz"
      sha256 "8ef3541303941bc98b888512333d45a00933a7a7dd664f1ec76b93659a70e897"
      define_method(:install) do
        bin.install "contrabass"
      end
    end
  end
end
